# Generated by Django 6.0.6 on 2026-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('product_description', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('tags', models.CharField(max_length=500)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx')],
            },
        ),
    ]
